#!/bin/bash

# Run the script containing list of packages 
echo "Generating package list..."
./generate_list_packages # this will run this script from the current directory

# Run the script with the installing details
echo "Running package installation..."
./install_packages # this will read the content from the packages.txt file and then install the listed packages

# Run the symbolic links creation script
echo "Creating symbolic links for configuration files..."
./symbolic_links # will create the symbolic link from the config files in our repository to correct location

# Confirmation message
echo "System setup complete."

